In [2]:
import os
os.environ['http_proxy']='127.0.0.1:7890'
os.environ['https_proxy']='127.0.0.1:7890'
from datasets import load_dataset

### 加载数据集

In [5]:
# cot datasets
dataset = load_dataset("TIGER-Lab/MathInstruct")
dataset = load_dataset("kaist-ai/CoT-Collection")

# other datasets
dataset = load_dataset("stanfordnlp/sst2")
dataset = load_dataset("ag_news")
dataset = load_dataset("trec")
dataset = load_dataset("EdinburghNLP/xsum")
dataset = load_dataset("Hello-SimpleAI/HC3")
dataset = load_dataset("sahil2801/CodeAlpaca-20k")

sst2 包含电影中的单句评价，用于语义分类任务

In [9]:
dataset = load_dataset("stanfordnlp/sst2")
dataset['train']['sentence'][:9]

['hide new secretions from the parental units ',
 'contains no wit , only labored gags ',
 'that loves its characters and communicates something rather beautiful about human nature ',
 'remains utterly satisfied to remain the same throughout ',
 'on the worst revenge-of-the-nerds clichés the filmmakers could dredge up ',
 "that 's far too tragic to merit such superficial treatment ",
 'demonstrates that the director of such hollywood blockbusters as patriot games can still turn out a small , personal film with an emotional wallop . ',
 'of saucy ',
 "a depressed fifteen-year-old 's suicidal poetry "]

ag-news 包含新闻文章，用于语义分类任务

In [16]:
dataset = load_dataset("ag_news")
dataset['train']['text'][:9]

["Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again.",
 'Carlyle Looks Toward Commercial Aerospace (Reuters) Reuters - Private investment firm Carlyle Group,\\which has a reputation for making well-timed and occasionally\\controversial plays in the defense industry, has quietly placed\\its bets on another part of the market.',
 "Oil and Economy Cloud Stocks' Outlook (Reuters) Reuters - Soaring crude prices plus worries\\about the economy and the outlook for earnings are expected to\\hang over the stock market next week during the depth of the\\summer doldrums.",
 'Iraq Halts Oil Exports from Main Southern Pipeline (Reuters) Reuters - Authorities have halted oil export\\flows from the main pipeline in southern Iraq after\\intelligence showed a rebel militia could strike\\infrastructure, an oil official said on Saturday.',
 'Oil prices soar to all-time record, posing new menace to US economy (A

trec 包含人工构建的问题，用于语义分类任务

In [18]:
dataset = load_dataset("trec")
dataset['train']['text'][:9]

['How did serfdom develop in and then leave Russia ?',
 'What films featured the character Popeye Doyle ?',
 "How can I find a list of celebrities ' real names ?",
 'What fowl grabs the spotlight after the Chinese Year of the Monkey ?',
 'What is the full form of .com ?',
 'What contemptible scoundrel stole the cork from my lunch ?',
 "What team did baseball 's St. Louis Browns become ?",
 'What is the oldest profession ?',
 'What are liver enzymes ?']

xsum 包含文章及文章总结，用于文本总结任务

In [3]:
dataset = load_dataset("EdinburghNLP/xsum")
texts = [f"Document:{document}Summary:{summary}" for document,summary in zip(dataset['train']['document'][0:9],dataset['train']['summary'][5:6])]
texts

Using the latest cached version of the dataset since EdinburghNLP/xsum couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /share/home/zhangshuhai/.cache/huggingface/datasets/EdinburghNLP___xsum/default/1.2.0/40db7604fedb616a9d2b0673d11838fa5be8451c (last modified on Mon May  6 15:37:10 2024).


['Document:The full cost of damage in Newton Stewart, one of the areas worst affected, is still being assessed.\nRepair work is ongoing in Hawick and many roads in Peeblesshire remain badly affected by standing water.\nTrains on the west coast mainline face disruption due to damage at the Lamington Viaduct.\nMany businesses and householders were affected by flooding in Newton Stewart after the River Cree overflowed into the town.\nFirst Minister Nicola Sturgeon visited the area to inspect the damage.\nThe waters breached a retaining wall, flooding many commercial properties on Victoria Street - the main shopping thoroughfare.\nJeanette Tate, who owns the Cinnamon Cafe which was badly affected, said she could not fault the multi-agency response once the flood hit.\nHowever, she said more preventative work could have been carried out to ensure the retaining wall did not fail.\n"It is difficult but I do think there is so much publicity for Dumfries and the Nith - and I totally appreciate 

hc3

In [7]:
dataset = load_dataset("Hello-SimpleAI/HC3","all")

Using the latest cached version of the module from /share/home/zhangshuhai/.cache/huggingface/modules/datasets_modules/datasets/Hello-SimpleAI--HC3/5af5910f9f3fe7aace30e32ad4c1ab776ca08183d00e9b2a091308549f69f683 (last modified on Mon May  6 15:20:12 2024) since it couldn't be found locally at Hello-SimpleAI/HC3, or remotely on the Hugging Face Hub.


In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'question', 'human_answers', 'chatgpt_answers', 'source'],
        num_rows: 24322
    })
})

In [11]:
texts = [f"Question:{question}Human_answers:{human_answers[0]}".replace(" .", ".").replace(" ? ","?").replace("\n","") for question,human_answers in zip(dataset['train']['question'][0:9],dataset['train']['human_answers'][0:9])]
texts

['Question:Why is every book I hear about a " NY Times # 1 Best Seller "?ELI5 : Why is every book I hear about a " NY Times # 1 Best Seller "?Should n\'t there only be one " # 1 " best seller?Please explain like I\'m five.Human_answers:Basically there are many categories of " Best Seller ". Replace " Best Seller " by something like " Oscars " and every " best seller " book is basically an " oscar - winning " book. May not have won the " Best film " , but even if you won the best director or best script , you \'re still an " oscar - winning " film. Same thing for best sellers. Also , IIRC the rankings change every week or something like that. Some you might not be best seller one week , but you may be the next week. I guess even if you do n\'t stay there for long , you still achieved the status. Hence , # 1 best seller.',
 "Question:If salt is so bad for cars , why do we use it on the roads?As the title states , why do we use it?is there no other option or what?Please explain like I'm f

Code 数据集

In [2]:
dataset = load_dataset("sahil2801/CodeAlpaca-20k")
dataset['train']

Dataset({
    features: ['output', 'instruction', 'input'],
    num_rows: 20022
})

In [8]:
dataset['train'][0]

{'output': 'arr = [2, 4, 6, 8, 10]',
 'instruction': 'Create an array of length 5 which contains all even numbers between 1 and 10.',
 'input': ''}

In [3]:
code_alpaca_20k_datas = [f"Instruction:{instruction}\nCode:{code}" for instruction,code in zip(dataset['train']['instruction'],dataset['train']['output'])]
code_alpaca_20k_examples = [["xsum_examples",code_alpaca_20k_datas]]
print(len(code_alpaca_20k_examples[0][1]))

20022


In [4]:
for sample in code_alpaca_20k_datas[:20]:
    print(sample)

Instruction:Create an array of length 5 which contains all even numbers between 1 and 10.
Code:arr = [2, 4, 6, 8, 10]
Instruction:Formulate an equation to calculate the height of a triangle given the angle, side lengths and opposite side length.
Code:Height of triangle = opposite side length * sin (angle) / side length
Instruction:Write a replace method for a string class which replaces the given string with a given set of characters.
Code:def replace(self, replace_with):
    new_string = ""
    for char in self:
        if char == " ":
            new_string += replace_with
        else:
            new_string += char
    return new_string
Instruction:Create an array of length 15 containing numbers divisible by 3 up to 45.
Code:arr = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45]
Instruction:Write a function to find the number of distinct states in a given matrix.
Code:def find_num_distinct_states(matrix):
    states = set()
    for row in matrix:
        state = "".join([s

In [21]:
import torch
def split_sentence(tokenizer,question,punctuation_id=2):
    inputs = tokenizer(question, padding=False, return_tensors='pt')
    input_ids = inputs['input_ids'].squeeze().cpu()
    print(input_ids)
    indices = []
    is_code=(True if 'Code' in tokenizer.name_or_path else False)
    if is_code is False:
        # 句号分割点
        full_stop_id = tokenizer('balls.',padding=False,return_tensors='pt')['input_ids'].squeeze()[punctuation_id].cpu()
        # 问号分割点
        question_mark_id = tokenizer('balls?',padding=False,return_tensors='pt')['input_ids'].squeeze()[punctuation_id].cpu()
        # 感叹号分割点
        exclamation_point_id = tokenizer('balls!',padding=False,return_tensors='pt')['input_ids'].squeeze()[punctuation_id].cpu()
        f_split_indices = torch.nonzero(torch.eq(input_ids, full_stop_id)).reshape(-1)
        q_split_indices = torch.nonzero(torch.eq(input_ids, question_mark_id)).reshape(-1)
        e_split_indices = torch.nonzero(torch.eq(input_ids, exclamation_point_id)).reshape(-1)
        indices += [f_split_indices,q_split_indices,e_split_indices]
    
    # 换行分割点
    n_stop_id = tokenizer('balls\n',padding=False,return_tensors='pt')['input_ids'].squeeze()[punctuation_id].cpu()
    f_n_split_indices = torch.nonzero(torch.eq(input_ids, n_stop_id)).reshape(-1)
    indices.append(f_n_split_indices)
    total_split = torch.cat(indices,dim=-1)
    sort_splits = torch.unique(torch.sort(total_split.view(-1)).values)
    print(sort_splits)
    return sort_splits

In [22]:
import sys
sys.path.append("..")
from transformers import AutoConfig, AutoTokenizer, AutoModelForCausalLM, TextStreamer, GenerationConfig
from config import *
path = path_llama_code_13b[1]
tokenizer = AutoTokenizer.from_pretrained(path, fast_tokenizer=True)
split_sentence(tokenizer,code_alpaca_20k_datas[0],punctuation_id=2)

tensor([    1,  2799,  4080, 29901,  4391,   385,  1409,   310,  3309, 29871,
        29945,   607,  3743,   599,  1584,  3694,  1546, 29871, 29896,   322,
        29871, 29896, 29900, 29889,    13,  3399, 29901,  2749,   353,   518,
        29906, 29892, 29871, 29946, 29892, 29871, 29953, 29892, 29871, 29947,
        29892, 29871, 29896, 29900, 29962])
tensor([23, 24])


tensor([23, 24])